version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: farfetch-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: farfetch_db
      MONGO_INITDB_ROOT_USERNAME: admin123
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
