version: '3.8'

services:
  zara-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zara-parser
    volumes:
      # Монтируем папку для сохранения результатов парсинга
      - ./data:/app/data
      # Монтируем папку для логов
      - ./logs:/app/logs
      # Монтируем конфиг (чтобы можно было менять без пересборки)
      - ./config.json:/app/config.json
    environment:
      - ZARA_COUNTRY=us
      - ZARA_LANG=en 
      - ZARA_CURRENCY=USD
      - ZARA_ITEMS_LIMIT=20  # товаров на категорию (уменьшено для надежности)
      - ZARA_REQUEST_DELAY_MIN=2.0  # увеличены задержки
      - ZARA_REQUEST_DELAY_MAX=4.0
      # Режимы: test, woman, man, full
      - ZARA_MODE=full
    restart: unless-stopped
    
  # Дополнительный сервис для быстрого тестирования
  zara-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zara-test
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    environment:
      - ZARA_COUNTRY=us
      - ZARA_LANG=en
      - ZARA_CURRENCY=USD
      - ZARA_ITEMS_LIMIT=3
      - ZARA_REQUEST_DELAY_MIN=1.0  # увеличили и для теста
      - ZARA_REQUEST_DELAY_MAX=2.0
      - ZARA_MODE=test
    profiles:
      - test
