version: "3.9"

services:
  zara-api-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zara-api-parser
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    volumes:
      # Монтируем директории для сохранения данных и логов
      - ./output:/app/output
      - ./logs:/app/logs
      # Монтируем директорию где будут сохраняться JSON файлы из api_en.py
      - .:/app/data
    command: >
      sh -c "
        echo 'Запуск Zara API парсера...' &&
        echo 'Время запуска: $(date)' &&
        python -u api_en.py --adults 2>&1 | tee /app/logs/parser_$(date +%%Y%%m%%d_%%H%%M%%S).log
      "
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # Ограничиваем ресурсы для экономии на AWS
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # Healthcheck для мониторинга
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f api_en.py > /dev/null || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - zara-network

  # Опциональный сервис для мониторинга логов через веб-интерфейс
  log-viewer:
    image: amir20/dozzle:latest
    container_name: zara-log-viewer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_LEVEL=info
    networks:
      - zara-network
    profiles:
      - monitoring  # Запускается только с профилем monitoring

networks:
  zara-network:
    driver: bridge
